### ISSUE TITLE
Enable mongo / redis for session management

### ISSUE THREAD

**Issue by JedWatson** [keystonejs/keystone-classic#41]
Keystone currently defaults to the in-memory datastore for the Session Express Middleware, which shouldn't be used in production.

There's a writeup on how to use redis or mongo for session management here:
http://blog.modulus.io/nodejs-and-express-sessions

**Comment by Phineas-z** [comment]
@kumo I have encountered the same problem, and found out that may be caused by the latest connect-mongo version. The latest version of connect-mongo can not work together with keystone, that is why ^0.4.1 is inappropriate, which would upgrade to 0.7.0. While ~0.4.1 will keep the version with 0.4.x, which is fine with keystone.

**Comment by sebmck** [comment]
@Phineas-z See #924

**Comment by JedWatson** [comment]
Just to clear this up:

Keystone <= 0.2.40 would not work with connect-mongo >= 0.5.0

Keystone 0.2.41 introduced compatibility with connect-mongo >= 0.5.0 but unfortunately broke compatibility with connect-mongo <= 0.4.1

This was fixed in 0.2.42, it and future versions should be compatible with _all_ versions of connect-mongo.

If you are experiencing problems with it please make sure you upgrade your keystone package, and if it's still broken please open a new issue with details.

Thanks!

**Comment by JedWatson** [comment]
**Also** to clear up misconceptions about `^` and `~`

See [the docs for semver](https://github.com/npm/node-semver#caret-ranges-123-025-004)

* `~` matches **patch updates** to the specified version (i.e. `~0.4.1` would allow `0.4.1` and `0.4.2` but not `0.4.0` or `0.5.0`, and `~1.4.1` would allow `1.4.1` and `1.4.2` but not `1.4.0` or `1.5.0`)
* `^` matches **any version that does not modify the left-most non-0 digit** (i.e. `^0.4.1` would allow `0.4.1` and `0.4.2` but not `0.4.0` or `0.5.0`, while `^1.4.1` would allow `1.4.1` and `1.4.2` **and** `1.5.0` but not `1.4.0` or `2.0.0`)

**Comment by dedric17** [comment]
Hi,
I'm currently configured to use mongo for my session store ('session store': 'mongo'), and it seems to work great. However, how can I set the session expiration time?  I'm using the session store to track browsing history of non-logged in users in order to exclude content they've already seen.  however, the session doesn't seem to expire.  Is there a config I am missing?

**Comment by morenoh149** [comment]
@dedric17 http://keystonejs.com/docs/configuration/#options-database see `session store options`

**Comment by akarsh** [comment]
@JedWatson 
the website link http://blog.modulus.io/nodejs-and-express-sessions
is broken
I tried searching on internetarchive. But, was not able to find it.
