### ISSUE TITLE
SQL?

### ISSUE THREAD

**Issue by jbaum98** [keystonejs/keystone-classic#645]
It seems like Mongoose is very central to the application, but is it possible to use an old fashioned SQL database instead of MongoDB?

**Comment by igl** [comment]
Mongo is easy if you do easy things.
SQL is hard but then you can do hard things easy when you learned it.

Mongo's lack of transactions and nerve-racking query ~~language~~syntax made us go to back to sql for our new project. After looking at the previous app with a year of development on it's back i only see disadvantages now.

Query: Queries using nested data structures are hard, ugly or simply impossible.
Forcing you to migrate back into a relational style data-structure defeats it's purpose imo. 
Schema: The advantage of being schema-less also gets defeated by mostly everybody using an ORM that implements... a schema.
No Transactions: While the case is rare (1/1000) Sometimes things just fail because you did not bump the write concern to `majority` and run a query too fast after another.

**Comment by costa974** [comment]
http://www.sarahmei.com/blog/2013/11/11/why-you-should-never-use-mongodb/

**Comment by Vandivier** [comment]
plug for a re-open. Here's a big deal for ya, Keystone: Some contracts (eg multimillion dollar DOD contracts) are locked into web development without allowing DB change. Guess what? Legacy DBs are SQL.

Also, SQL definitely has its use cases. Any time data loss is unacceptable, full ACID is required (including complex, mult-doc transactions), or a well-defined schema will be utilized for heavy computation including aggregate statistical reports.

https://www.reddit.com/r/mongodb/comments/43m2om/how_exactly_does_mongodb_lose_data_and_is_it/

https://stackoverflow.com/questions/7149890/what-does-mongodb-not-being-acid-compliant-really-mean

As a principle developer on such a DOD contract, the main reason I am not suggesting Keystone is SQL incompatibility. (also I'd like to see React in the public ui, not just admin ui, but that is minor and we would be able to mod that)

**Comment by bellsaladin** [comment]
I've started a project with the goal to support Mysql. The project has now a good foundation & implementation strategy.
https://github.com/bellsaladin/Keystone-Mysql

I have been using Keystone for quite a while now as light admin tool for some small projects and I aquired good knowledge on it's core functionning, at some point i felt the need for Mysql databases support, so i started a project with that goal.

I work on this project on free time only so I need help for this project to progress. **Any help is welcome**.
